[versions]
agp = "8.2.2"
ksp = "1.9.21-1.0.15"
kotlin = "1.9.0"
core-ktx = "1.12.0"
lifecycle-runtime-ktx = "2.7.0"
lifecycle-process = "2.7.0"
activity-compose = "1.8.2"
navigation-compose = "2.7.7"
compose-bom = "2024.02.00"

koin = "3.5.3"
room = "2.6.1"
gson = "2.10.1"
coil = "2.5.0"
dataStore = "1.0.0"
work = "2.9.0"

junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle-process"}

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

material3 = { group = "androidx.compose.material3", name = "material3" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose-navigation", version.ref = "koin" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
workKtx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work"}

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
